server:
  port: 8080
  servlet:
    context-path : /
spring:
  mvc :
    view :
      prefix : /WEB-INF/view/
      suffix : .jsp
  main :
    allow-bean-definition-overriding: true

  profiles:
    include: oauth

  web:
    resources:
      static-locations:
  datasource:
    #Postgresql -> H2로 변경 rollback
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/guide
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:tcp://localhost/~/test
    username: dubbi
    password: dubbi

  thymeleaf:
    cache: true

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      platform: postgres

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id : 4aMykJn0RKbePnHmiEEZ
            client-secret : uGPlwDdTgW
            redirect-uri : http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type : authorization_code
            scope : profile_image, email, name
            client-name : Naver
          google:
            client-id: 312928443884-fmgg4emldrvhah9e1927kkrn0r4dcpqh.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          kakao:
            client-id: e5f46a5f25a9b842189f432833b8d641
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver :
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response